### ISSUE TITLE
Löschen von "Steps"

### ISSUE THREAD

**Issue by LoLBr4iN** [JFARM2016/ProjectHungry#1]
Idee: Durch langes drücken und halten auf einen "Step" Mülleimer für alle "Steps" möglich machen. Analog zur "Medienleiste", wie aus der Apple App.

@FloriVonDerGPC Wollen wir das auf "Zubereitung" und "Zutaten" (etc.) hinzufügen? Wenn ja, dann bitte auf den Folien kurz hinzufügen

**Comment by FloriVonDerGPC** [comment]
Verstehe ich nicht... In welchem Screen?

**Comment by FloriVonDerGPC** [comment]
Neue Überlegung zum Löschen: Titel-Leiste wird bei Drag & Drop Funktionen zu einer "Lösch-Leiste" auf die die Elemente gezogen werden können. @Jerry0022 wird das mal prototypartig umsetzen, dann schauen wir mal wie die User Experience ist :-)

**Comment by FloriVonDerGPC** [comment]
@Jerry0022 können wir closen, oder?
