### ISSUE TITLE
Media Klasse funktioniert nicht richtig

### ISSUE THREAD

**Issue by Jerry0022** [JFARM2016/ProjectHungry#11]
Ich habe mir mal per @ToString den Inhalt von erstellten Media angeschaut. Teils war der type falsch, teils kein mime type und weitere komische Punkte.
Am Besten mal einen intensiv check machen, dass alle Pojos richtig befüllt werden in den jeweiligen Situationen, ansonsten rennen wir noch tagelang irgendwelchen Fehlern nach.

**Comment by spike-rabbit** [comment]
mime-solved
