### ISSUE TITLE
FAB Fehlermeldung

### ISSUE THREAD

**Issue by Jerry0022** [JFARM2016/ProjectHungry#19]
eu.eatable I/FloatingActionButton: Setting a custom background is not supported.

erscheint nach dem App Öffnen im Log.

**Comment by FloriVonDerGPC** [comment]
ja stimmt, man findet dazu nichts in den Foren.. nur dass google den Hinweis in die FAB-Java Datei geschrieben hat und übers Log ausgibt... warum auch immer. Wir machen eigentlich alles so wie es auch generell in stackoverflow empfohlen wird
