### ISSUE TITLE
Thumbnail Größe falsch?

### ISSUE THREAD

**Issue by Jerry0022** [JFARM2016/ProjectHungry#20]
Hey,

nachdem ich ein Bild hinzugefügt habe **und** dann auf einen Step ziehe, kommt folgendes im Log:
04-23 11:29:30.610 2846-2846/eu.eatable I/libencoder: width= 5312, height = 2988, colot_type= 2, bit_depth= 8
Komprimierst du das Bild als Thumbnail in der Media? Bitte nochmal die Breite/Höhe checken.

**Comment by spike-rabbit** [comment]
Ich glaube, ich habs gelöst. Überprüf das mal. Ich kriege den Log eintrag nicht.
