### ISSUE TITLE
Default-Tabs lassen sich ersetzen

### ISSUE THREAD

**Issue by FloriVonDerGPC** [JFARM2016/ProjectHungry#23]
Gerade entdeckt... wenn man einen neuen Tab (NewTabField) hinzufügt und diesen Tab genauso nennt wie die Standard-Tabs (Quick Mode, Zubereitung, Zutaten, Tags, +) wird das neue Tab Element angeklickt im NewTabField (weil es ja schon existiert). Wähle ich das neue Icon ab, wird der Standard-Tab gelöscht.
Ich würde sagen, dass wir Standardfelder (Quick Mode, Zubereitung, Zutaten, Tags, +) beim Hinzufügen neuer Tabs abfangen und unterbinden?

**Comment by Jerry0022** [comment]
fixed, aber noch nicht gepushed. Auf Grund von wiederauftauchen von Altbugs

**Comment by Jerry0022** [comment]
fixed auch der wiederkehrenden alt bugs
