### ISSUE TITLE
Multi-Line beim Dialog im Hinzufügescreen

### ISSUE THREAD

**Issue by FloriVonDerGPC** [JFARM2016/ProjectHungry#3]
Momentan schreibt man "über die Grenzen hinaus". Besser wäre, wenn der Text automatisch in die nächste Zeile springt.

**Comment by Jerry0022** [comment]
Fixed.

**Comment by Jerry0022** [comment]
Läuft noch nicht -> Jetzt funktioniert Enter nicht mehr...
