### ISSUE TITLE
Access Context in persistenceUnit

### ISSUE THREAD

**Issue by spike-rabbit** [JFARM2016/ProjectHungry#5]
Ich brauche den Context zum Bearbeiten von Uris und um MimeTypes zu ermitteln.
Die zweite Lösung sieht am besten aus.

Bitte möglichst schnell auf den Master.
[http://stackoverflow.com/questions/7157501/is-it-possible-to-get-applications-context-in-an-android-library-project](url)

**Comment by Jerry0022** [comment]
Siehe App.java auf dem New eatable Branch

**Comment by spike-rabbit** [comment]
Die liegt im falschem modul
Am 31.03.2016 6:50 nachm. schrieb "Jerry" <notifications@github.com>:
