### ISSUE TITLE
Thumnail-Size

### ISSUE THREAD

**Issue by spike-rabbit** [JFARM2016/ProjectHungry#6]
@Jerry0022 @FloriVonDerGPC 
Welche Größe sollen die Thumbnails haben?

**Comment by FloriVonDerGPC** [comment]
Willst du height und width wissen? Wenn ja, 60dp

**Comment by spike-rabbit** [comment]
Ja
Am 18.04.2016 8:01 nachm. schrieb "FloriVonDerGPC" <notifications@github.com
