### ISSUE TITLE
Tag/Tabs - Anzahl in der Breite im Grid

### ISSUE THREAD

**Issue by Jerry0022** [JFARM2016/ProjectHungry#8]
Wird auf dem Puls falsch dargestellt. Lediglich Platz für drei.

**Comment by FloriVonDerGPC** [comment]
![screenshot 19 04 2016 22_49_08](https://cloud.githubusercontent.com/assets/9432143/14685002/cdd527b4-0732-11e6-9028-2935c875ba0c.png)

**Comment by Jerry0022** [comment]
Im Tab Feld funktioniert es, bitte im UnorderedFieldTab in Zeile 65 die Breite ändern

**Comment by FloriVonDerGPC** [comment]
Also im Tab Feld sieht es bei mir genauso aus wie im Tag Feld... bei dir etwa nicht? ❓

**Comment by Jerry0022** [comment]
Ne, bei mir nicht. Hier müssen wir uns wohl nochmal zusammentelefonieren.

**Comment by FloriVonDerGPC** [comment]
probier mal nochmal, habe nochmals angepasst und jetzt scheint es zu laufen... @Jerry0022

**Comment by Jerry0022** [comment]
Sieht jetzt gut aus
